


export const metadata = {
    title: 'View Detail Blog',
    description: 'Generated by Bao Loc',
  }
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    {children}
    </>
        
        
  )
}
